### ISSUE TITLE
Filenames with unconventional names

### ISSUE THREAD

**Issue by janvanrijn** [mlindauer/asapy#5]
In the OASC repo, there are some asapy reports checked in with filenames including a star. These filenames highly complicate stuff on Windows, in particular when using git.

**Comment by mlindauer** [comment]
hmm... this only happens if an algorithm or instance has a star in its name. 

Actually, I don't actively support Windows and I have no clue whether someone could run asapy on Windows. Sorry, thus I don't plan to fix this.

**Comment by janvanrijn** [comment]
Off topic but could you please remove the asapy files from the OASC repo (https://bitbucket.org/mlindauer/oasc/overview) to a separate branch or a zip file? Currently I can't do anything with the repo except copy/pasting my adjusted files into the web editor

**Comment by mlindauer** [comment]
Sorry; I was not aware that this would be in issue on windows.
I removed these files in the oasc repo.

**Comment by janvanrijn** [comment]
Thanks!
